[package]
name = "mesh-bindings"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "mesh_bindings"
crate-type = ["cdylib", "staticlib", "lib"]

[dependencies]
mesh-core = { path = "../mesh-core" }
mesh-crypto = { path = "../mesh-crypto" }
mesh-types = { path = "../mesh-types" }
rand_core.workspace = true
thiserror.workspace = true
uniffi.workspace = true
zeroize.workspace = true

[features]
cli = ["uniffi/cli"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
required-features = ["cli"]

